# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e21f1abc812518a56cbd2b393e1e4dd4de59b6a0d3eb92a394753fcf468f3792acea2dd2607808420016ec5969d80a63bf235c837121ea82423442582dd8d4e

test:
  secret_key_base: 5c7fd1a43214fe854864c39faa721090c6c928d982fe81c3e88684b546204f195571fe59124ce230d4cf07661d72909a5e9cbc3e5fd2a27bd874dd871356edae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
